### ISSUE TITLE
Bokeh 2.0 is imminent

### ISSUE THREAD

**Issue by bryevdv** [spotify/chartify#104]
Just a heads-up that Bokeh 2.0 will be coming out in the next week or so. At a minimum you may want to release packages that versions to <2.0 if they are not already. Whenever you look to update packages for Bokeh 2.0 compat we'd be happy to help over at the Development topic on the Discourse:

https://discourse.bokeh.org/c/development/7

**Comment by cphalpert** [comment]
Thanks for the heads up! will look into upgrading

**Comment by cphalpert** [comment]
#109
