### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by mjdavsge71** [spotify/chartify#23]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
type: bug
> type: feature

**Environment**:

- Chartify version(s): installed latest via pip install chartify
- Operating System(s): Wind 10
- Python version(s): Anaconda 4.5.4

**What happened**:
jupyter notebook, tried to import charify

ImportError: DLL load failed: The specified module could not be found.
**What you expected to happen**:
charitify to import
**How to reproduce it (as minimally and precisely as possible)**:
get the error anytime I try to import charity, I uninstalled it and reinstalled via pip still same error
**Anything else we need to know?**:
ImportError                               Traceback (most recent call last)
<ipython-input-2-e4ea3e2db907> in <module>()
----> 1 import chartify

C:\Users\msavage\AppData\Local\Continuum\anaconda3\lib\site-packages\chartify\__init__.py in <module>()
     15 # limitations under the License.
     16 """Top-level package for chartify."""
---> 17 from chartify._core.chart import Chart
     18 from chartify._core.colors import color_palettes
     19 from chartify._core.options import options

C:\Users\msavage\AppData\Local\Continuum\anaconda3\lib\site-packages\chartify\_core\chart.py in <module>()
     24 
     25 import bokeh
---> 26 import bokeh.plotting
     27 from bokeh.embed import file_html
     28 

C:\Users\msavage\AppData\Local\Continuum\anaconda3\lib\site-packages\bokeh\plotting\__init__.py in <module>()
      1 # this is just for testing, otherwise the figure module is shadowed
      2 # by the figure function and inacessible
----> 3 from . import figure as _figure
      4 
      5 # extra imports -- just things to add to 'from bokeh.plotting import'

C:\Users\msavage\AppData\Local\Continuum\anaconda3\lib\site-packages\bokeh\plotting\figure.py in <module>()
      6 from six import string_types
      7 
----> 8 from ..core.properties import Any, Auto, Either, Enum, Int, List, Seq, Instance, String, Tuple
      9 from ..core.enums import HorizontalLocation, MarkerType, VerticalLocation
     10 from ..models import ColumnDataSource, Plot, Title, Tool, GraphRenderer

C:\Users\msavage\AppData\Local\Continuum\anaconda3\lib\site-packages\bokeh\core\properties.py in <module>()
    254 from .property.container import RelativeDelta; RelativeDelta
    255 
--> 256 from .property.dataspec import AngleSpec; AngleSpec
    257 from .property.dataspec import ColorSpec; ColorSpec
    258 from .property.dataspec import DataSpec; DataSpec

C:\Users\msavage\AppData\Local\Continuum\anaconda3\lib\site-packages\bokeh\core\property\dataspec.py in <module>()
     39 from .instance import Instance
     40 from .primitive import Float, String
---> 41 from .visual import FontSize, MarkerType
     42 
     43 #-----------------------------------------------------------------------------

C:\Users\msavage\AppData\Local\Continuum\anaconda3\lib\site-packages\bokeh\core\property\visual.py in <module>()
     28 
     29 # External imports
---> 30 import PIL.Image
     31 from six import string_types
     32 

C:\Users\msavage\AppData\Local\Continuum\anaconda3\lib\site-packages\PIL\Image.py in <module>()
     56     # Also note that Image.core is not a publicly documented interface,
     57     # and should be considered private and subject to change.
---> 58     from . import _imaging as core
     59     if PILLOW_VERSION != getattr(core, 'PILLOW_VERSION', None):
     60         raise ImportError("The _imaging extension was built for another "

ImportError: DLL load failed: The specified module could not be found.

**Comment by cphalpert** [comment]
This seems to be an issue with the Pillow dependency and your anaconda environment rather than with chartify:

[](https://github.com/python-pillow/Pillow/issues/2945)

[](https://stackoverflow.com/questions/43264773/pil-dll-load-failed-specified-procedure-could-not-be-found
)

I would try uninstalling and reinstalling pillow as suggested in the links above.
