### ISSUE TITLE
Any way to render charts on web?

### ISSUE THREAD

**Issue by brandonmcconnell** [spotify/chartify#24]
Is there any way to have the charts render on web so I can style and animate them on the fly and potentially make them interactive with data from my database?

**Comment by cphalpert** [comment]
Thus far we've focused on the use case of static charts that go into presentations.

For interactive visualizations I'd suggest using base [Bokeh interactions](http://bokeh.pydata.org/en/latest/docs/user_guide/interaction.html) with [Bokeh Server](http://bokeh.pydata.org/en/latest/docs/user_guide/server.html) or [Plotly with Dash](https://plot.ly/products/dash/).
