### ISSUE TITLE
selenium and chromedriver dependenices 

### ISSUE THREAD

**Issue by Tagar** [spotify/chartify#30]
Is there is a way to avoid chromedriver install to just render png output? 

Is this possible to switch to another way of generating pngs? 

What's advantage of crhomedriver?

ps. I also noticed selenium dependency - how is chartify related to automated testing? 

Thanks!

**Comment by cphalpert** [comment]
Bokeh (the library that Chartify is built off of) generates charts in HTML format. Chromedriver and selenium are used to automate the process of converting from HTML to PNG. A headless browser renders the HTML and saves the screenshot as PNG. Bokeh uses [PhantomJS](http://bokeh.pydata.org/en/latest/docs/user_guide/export.html#png-generation) but I switched over to chrome to increase the PNG quality.

As an alternative to installing chromedriver you can also manually click on the save icon in a HTML chart and it'll save the chart as PNG using your browser.

**Comment by Tagar** [comment]
thank you @cphalpert
