### ISSUE TITLE
subtitle covered by legend if legend location set to "outside_top"

### ISSUE THREAD

**Issue by simonwongwong** [spotify/chartify#34]
**Is this a BUG REPORT or FEATURE REQUEST?**:

type: bug

**Environment**:

- Chartify version(s): 2.3.4
- Operating System(s): Windows 10
- Python version(s): 3.7.0

**What happened**:
If `ch.set_legend_location("outside_top")` is evaluated after a subtitle is created, it will cover the subtitle. Not an issue if the subtitle is created after `ch.set_legend_location("outside_top")` .

**What you expected to happen**:
Expected subtitle to appear 

**How to reproduce it (as minimally and precisely as possible)**:
Create a chart with a subtitle then add the legend to "outside_top"

**Anything else we need to know?**:
It's still possible to have both subtitle and `outside_top` legend if the subtitle is added afterwards.

**Comment by simonwongwong** [comment]
With subtitle set before legend:

![image](https://user-images.githubusercontent.com/17996988/48850038-a6c9ce00-ed75-11e8-847a-295ef8777fdf.png)


With subtitle set after legend:

![image](https://user-images.githubusercontent.com/17996988/48849830-33c05780-ed75-11e8-99fd-d398caa7b56d.png)

**Comment by cphalpert** [comment]
Thanks for reporting the bug!
