### ISSUE TITLE
Annotating the graph with horizontal and vertical lines

### ISSUE THREAD

**Issue by troyshu** [spotify/chartify#59]
**Is this a BUG REPORT or FEATURE REQUEST?**:

type: feature

Maybe this is already possible with Chartify and I missed it, but it would be great if Chartify provided an easy way to overlay/add horizontal and vertical lines (of different colors, different dash patterns) to a graph! e.g. to represent levels, or dates of specific events, on the graph.

**Comment by cphalpert** [comment]
Check out the line callouts:
https://github.com/spotify/chartify/blob/master/chartify/_core/callout.py#L41

There's a section for usage in the examples notebook: https://github.com/spotify/chartify/blob/master/examples/Examples.ipynb

**Comment by troyshu** [comment]
Oh I see, thanks so much @cphalpert!
