### ISSUE TITLE
Unable to show the legend

### ISSUE THREAD

**Issue by robyf70** [spotify/chartify#75]
Hi,

I've an issue regarding how to print the legend with a simple set of data like below:

    accel_speed  accel_g1  accel_g2  accel_g3  accel_g4  accel_g5  accel_g6
0             0  0.000000  0.000000  0.000000  0.000000       0.0       0.0
1             1  0.000000  0.000000  0.000000  0.000000       0.0       0.0
2             2  0.000000  0.000000  0.000000  0.000000       0.0       0.0
3             3  0.000000  0.000000  0.000000  0.000000       0.0       0.0
4             4  0.000000  0.000000  0.000000  0.000000       0.0       0.0
5             5  0.000000  0.000000  0.000000  0.000000       0.0       0.0
6             6  2.813216  0.000000  0.000000  0.000000       0.0       0.0
7             7  3.653817  0.000000  0.000000  0.000000       0.0       0.0
8             8  2.807802  0.000000  0.000000  0.000000       0.0       0.0
9             9  2.312193  0.555871  0.000000  0.000000       0.0       0.0
10           10  3.660337  1.154770  0.000000  0.000000       0.0       0.0

that I would like to line plot as `accel_speed` vs `accel_gX`, so currently I'm the code below to fill the chart

            for k in data.keys():
                if k != 'accel_speed':
                    ch.plot.line(data_frame=df, y_column=k, x_column='accel_speed')

But I don't know how to specify the legend. Finally is there a way to plot such multi column data in one shot such as `ch.plot.multi_line()`?

Thank you,
Roberto Fichera.

**Comment by cphalpert** [comment]
Hi Roberto,

Currently chartify expects all the data to be in a grouped format for legends to work properly. To plot multiple lines you can melt the pivot table and pass the appropriate dimension to the `color_column` parameter. See the pivoted data section of https://github.com/spotify/chartify/blob/master/examples/Chartify%20Tutorial.ipynb

Long term, it would be good to have a feature to allow for line graphs from pivoted data -- I'll add a feature in with this suggestion. Thanks!
