### ISSUE TITLE
ValueError: Bad 'legend' parameter value: None

### ISSUE THREAD

**Issue by jpkoc** [spotify/chartify#96]
Hi,
I updated to the latest version of bokeh yesterday and get now this warning:
`BokehDeprecationWarning: 'legend' keyword is deprecated, use explicit 'legend_label', 'legend_field', or 'legend_group' keywords instead

followed by:
ValueError: Bad 'legend' parameter value: None

The issue seems to be related to the following section of the plot.py code
1397         if color_column:
1398            legend = bokeh.core.properties.field('color_column')
1399        else:
1400            legend = None

Please could you tell me how to fix this.
Thank you

**Comment by xiangxingxing** [comment]
I meet the same issure and hope to get a solution too.

**Comment by cphalpert** [comment]
Thanks for surfacing the issue! I'll release a fix in the next few days. In the meantime downgrading bokeh should fix the issue

**Comment by xiangxingxing** [comment]
> Thanks for surfacing the issue! I'll release a fix in the next few days. In the meantime downgrading bokeh should fix the issue

Many thanks.

**Comment by cphalpert** [comment]
#98
